server:
  port: 8031
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HelloKTKT/configServer
          searchPaths: config
          #username: your-username
          #password: your-password
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server1:8100/eureka,http://server2:8200/eureka,http://server3:8300/eureka
logging:
  config: classpath:log4j-test.xml


