####服务端口号
#server:
#  port: 8100
#
####服务名称
#spring:
#  application:
#    name: eureka-server
#
#eureka:
#  instance:
#    #注册中心地址
#    hostname: 127.0.0.1
#  ###客户端调用地址
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
#    ###是否将自己注册到Eureka服务中,因为该应用本身就是注册中心，不需要再注册自己（集群的时候为true）
#    register-with-eureka: false
#    ###是否从Eureka中获取注册信息,因为自己为注册中心,不会在该应用中的检索服务信息
#    fetch-registry: false

spring:
  application:
    name: eureka-server-cluster
#  security:
#    basic:
#      enabled: true
#    user:
#      name: admin
#      password: admin

logging:
  config: classpath:log4j-test.xml

