server:
  port: 8041
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: gateway-service
          uri: lb://service-consumer
          predicates:
            - Path=/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server1:8100/eureka,http://server2:8200/eureka,http://server3:8300/eureka
logging:
  config: classpath:log4j-test.xml
